### ISSUE TITLE
Creating poly-data suitable for use

### ISSUE THREAD

**Issue by Jimbles** [dengwirda/mesh2d#4]
Hey,
I was wondering how you would suggest creating a file like the airfoil.msh or lake.msh from a histological section like this: [histological slice](https://i.imgur.com/eji57BY.png). I would want to define the layers as edges so I can refine the mesh at each transition. They might be more complicated than just a straight lines, otherwise I would define them like in tridemo(0)
Cheers!

**Comment by dengwirda** [comment]
Okay - it looks like there is quite a lot going on in that data slice! I'm not sure that I understand exactly what you're looking for in terms of geometry.

One option to try might be 'iso-level/contour extraction' - using the `contour` function to extract a grey-scale level that then defines a polygonal boundary. The trick is to try to choose an appropriate grey-scale value... I've just added the `getiso2` function to `mesh2d` that may be helpful here.

**Comment by krober10nd** [comment]
Hey,

I might add that if your data is geospatial in nature, then GRASS GIS's
r.contour module may be quite useful to extract one and then use that as
the PSLG.

Contours can be often quite disconnected and the r.cut parameter (cut=150
or so) in GRASS can help ensure it's not disjoint.

Hope it helps

**Comment by dengwirda** [comment]
@krober10nd absolutley - if the contour is noisy and/or poorly-connected then some kind of additional filtering/clean-up may well be necessary. The `getiso2` routine I included just uses the standard `contour` function, so is non-fancy in this way.

**Comment by Jimbles** [comment]
hey,
Thank you both very much for your quick replies! I will have a play with those routines mentioned. I think they should do the trick!

**Comment by dengwirda** [comment]
No worries -- I'll close this for now, but feel free to get back to me if you have any further questions.

**Comment by Jimbles** [comment]
Hey, I wanted to update you and thank you again for the help. I made an example of the mesh creation [here](https://gist.github.com/Jimbles/47460bda9cb93120918221e5894da0dc) in case anyone was interested. I found [Decimate Polygon](https://uk.mathworks.com/matlabcentral/fileexchange/34639-decimate-polygon) to be useful in cleaning up the contours - there were not manifold otherwise. [This](https://uk.mathworks.com/matlabcentral/fileexchange/30793-smoothing-2d-contours-using-local-regression-lines) could be useful for smoothing contours in the future.

I was wondering if you had any advice about preventing the kind of lines seen [here](https://i.imgur.com/jNya5EU.png) as they are impacting the results of the solver i am using like [this](https://i.imgur.com/FoKzf3o.png). 

Thanks!

**Comment by dengwirda** [comment]
@Jimbles Great, glad to hear that this is working -- using a decimation algorithm should be a good option to clean up complex polygons. The [Ramer-Douglas-Peuker](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm) algorithm might be useful here as well.

In terms of the 'lines' you mention (where the mesh elements change orientation slightly) I'd actually suggest this may represent an issue with the solver, rather than the mesh. Generally, it's not possible to fill a domain with perfect elements, so ideally the solver should be able to handle configurations that include some slightly non-equilateral triangles. The kind of 'grid-imprinting' that you've shown sometimes occurs when the underlying numerical scheme is only 1st-order accurate. If it's possible to switch to a higher-order formulation, the artefacts in the solution should hopefully disappear.

**Comment by Jimbles** [comment]
@dengwirda thanks again. That algorithm might be a better fit for what I need I will check it out! Im playing around with custom sizing fields to also refine closer to the sources and detectors. Im finding things in this repo very useful. Thanks!

Unfortunately I didnt write the solver so it is something of a black box. I am plotting the sensitivity/jacobian matrix so it might be that I am not visualising it correctly. As smaller elements would have a smaller sensitivity, but the "bulk" sensitivity across many elements is likely to be unchanged
