### ISSUE TITLE
acute triangulation

### ISSUE THREAD

**Issue by karimnorouzi** [dengwirda/mesh2d#5]
Hi, this is not an issue per say. I was wondering how to make a constrained delaunay where all triangles are acute ?

**Comment by dengwirda** [comment]
In general, it's not necessarily so easy to generate all-acute delaunay triangulations. In particular, the theory behind most delaunay-refinement schemes (including the implementation in `MESH2D`) typically only guarantees angles `< 120 deg`.

As far as I know, most algorithms for the all-acute CDT problem employ some kind of optimisation-based approach -- a combination of moving vertices, flipping topology, merging / splitting edges, re-meshing, etc. `JIGSAW` (the more sophisticated partner to `MESH2D`) includes some algorithms to do this kind of thing. Other authors have also invented different optimisation approaches.

In some cases, rather than looking for an all-acute triangulation, the goal is actually to build a dual grid (i.e. a Voronoi-like tessellation) that is *well-centred* -- with each dual vertex located inside its associated triangle. Such grids are often desirable for numerical simulation. In this case, a better approach may be to build a kind of 'weighted' delaunay triangulation -- achieving well-centred configurations even when the triangulation itself includes some non-acute angles. Recent versions of `JIGSAW` pursue such approaches.

**Comment by karimnorouzi** [comment]
I looked at jigsaw and compiled it under linux. It compiles and is ready to go. However, can it act on an existing mesh and optimize the mesh ? I can produce a mesh with triangle and feed it to jigsaw to do its magic and produce well-centered mesh if jigsaw can accept existing triangulation.

**Comment by dengwirda** [comment]
Let me first push some updates to `JIGSAW` today -- I've recently added the possibility to load meshes via an initial conditions file, and you may be able to use this workflow to run the optimiser on a mesh generated by Triangle, say. I'll let you know when this is ready to go.
